ARG VARIANT="24"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:${VARIANT}

RUN apt-get update && apt-get -y install --no-install-recommends curl git sqlite3

USER node
RUN npm install -g @sap/cds-dk
WORKDIR /home/node